/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppShearersRouteImport } from './routes/app.shearers'
import { Route as AppSellRouteImport } from './routes/app.sell'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppFlockRouteImport } from './routes/app.flock'
import { Route as AppClassifyRouteImport } from './routes/app.classify'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppBookingsRouteImport } from './routes/app.bookings'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppResultIdRouteImport } from './routes/app.result.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppShearersRoute = AppShearersRouteImport.update({
  id: '/shearers',
  path: '/shearers',
  getParentRoute: () => AppRoute,
} as any)
const AppSellRoute = AppSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppFlockRoute = AppFlockRouteImport.update({
  id: '/flock',
  path: '/flock',
  getParentRoute: () => AppRoute,
} as any)
const AppClassifyRoute = AppClassifyRouteImport.update({
  id: '/classify',
  path: '/classify',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppResultIdRoute = AppResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/classify': typeof AppClassifyRoute
  '/app/flock': typeof AppFlockRoute
  '/app/profile': typeof AppProfileRoute
  '/app/sell': typeof AppSellRoute
  '/app/shearers': typeof AppShearersRoute
  '/app/support': typeof AppSupportRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset': typeof AuthResetRoute
  '/app/': typeof AppIndexRoute
  '/app/result/$id': typeof AppResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/classify': typeof AppClassifyRoute
  '/app/flock': typeof AppFlockRoute
  '/app/profile': typeof AppProfileRoute
  '/app/sell': typeof AppSellRoute
  '/app/shearers': typeof AppShearersRoute
  '/app/support': typeof AppSupportRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset': typeof AuthResetRoute
  '/app': typeof AppIndexRoute
  '/app/result/$id': typeof AppResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/classify': typeof AppClassifyRoute
  '/app/flock': typeof AppFlockRoute
  '/app/profile': typeof AppProfileRoute
  '/app/sell': typeof AppSellRoute
  '/app/shearers': typeof AppShearersRoute
  '/app/support': typeof AppSupportRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/reset': typeof AuthResetRoute
  '/app/': typeof AppIndexRoute
  '/app/result/$id': typeof AppResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/admin'
    | '/app/bookings'
    | '/app/calendar'
    | '/app/classify'
    | '/app/flock'
    | '/app/profile'
    | '/app/sell'
    | '/app/shearers'
    | '/app/support'
    | '/auth/confirm'
    | '/auth/reset'
    | '/app/'
    | '/app/result/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app/admin'
    | '/app/bookings'
    | '/app/calendar'
    | '/app/classify'
    | '/app/flock'
    | '/app/profile'
    | '/app/sell'
    | '/app/shearers'
    | '/app/support'
    | '/auth/confirm'
    | '/auth/reset'
    | '/app'
    | '/app/result/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/app/admin'
    | '/app/bookings'
    | '/app/calendar'
    | '/app/classify'
    | '/app/flock'
    | '/app/profile'
    | '/app/sell'
    | '/app/shearers'
    | '/app/support'
    | '/auth/confirm'
    | '/auth/reset'
    | '/app/'
    | '/app/result/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shearers': {
      id: '/app/shearers'
      path: '/shearers'
      fullPath: '/app/shearers'
      preLoaderRoute: typeof AppShearersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sell': {
      id: '/app/sell'
      path: '/sell'
      fullPath: '/app/sell'
      preLoaderRoute: typeof AppSellRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/flock': {
      id: '/app/flock'
      path: '/flock'
      fullPath: '/app/flock'
      preLoaderRoute: typeof AppFlockRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classify': {
      id: '/app/classify'
      path: '/classify'
      fullPath: '/app/classify'
      preLoaderRoute: typeof AppClassifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/result/$id': {
      id: '/app/result/$id'
      path: '/result/$id'
      fullPath: '/app/result/$id'
      preLoaderRoute: typeof AppResultIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBookingsRoute: typeof AppBookingsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClassifyRoute: typeof AppClassifyRoute
  AppFlockRoute: typeof AppFlockRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSellRoute: typeof AppSellRoute
  AppShearersRoute: typeof AppShearersRoute
  AppSupportRoute: typeof AppSupportRoute
  AppIndexRoute: typeof AppIndexRoute
  AppResultIdRoute: typeof AppResultIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBookingsRoute: AppBookingsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClassifyRoute: AppClassifyRoute,
  AppFlockRoute: AppFlockRoute,
  AppProfileRoute: AppProfileRoute,
  AppSellRoute: AppSellRoute,
  AppShearersRoute: AppShearersRoute,
  AppSupportRoute: AppSupportRoute,
  AppIndexRoute: AppIndexRoute,
  AppResultIdRoute: AppResultIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmRoute: AuthConfirmRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
